version: '3.8'

services:
  jekyll:
    build: .
    command: jekyll serve --force_polling --trace
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
    restart: unless-stopped